// test/ExportService.unit.test.js
/**
 * Unit tests for ExportService.
 *
 * Focus:
 * - export structure stability
 *
 * All Google Apps Script dependencies are mocked via: initTestKernel in text/utils/testKernel.js,
 * which sets up the necessary environment for testing without actual GAS services.
 */

// eslint-disable-next-line
const { ExportService, ExportStickers } = require('../build/ExportService.js')

/** Helper method to be used in both parsers */
function parseCodeAndIcon (first, includeFlags) {
  if (!includeFlags || !first.includes(' ')) {
    return { code: first, icon: null }
  }
  const split = first.trim().split(/\s+/)
  return { icon: split[0], code: split.slice(1).join(' ') }
}

/**
 * Parses exportSharedData output into structured testable object.
 * Supports compact and non-compact formats and optional flag (icon) inclusion.
 *
 * @param {string} text - Raw exportSharedData output string.
 * @param {{ isCompact?: boolean, includeFlags?: boolean }} options - Parsing options.
 * @return {{ repeats: { items: Array<{code:string,icon:string,tokens:Array<string>}>, fallback: string|null },
 *  missing: { items: Array<{code:string,icon:string,tokens:Array<string>}>, fallback: string|null } }}
 *  Parsed data structure with repeats and missing sections.
 */
function parseExportSharedData (text, { includeFlags = false } = {}) {
  const lines = text.split('\n').filter(Boolean)
  const result = { repeats: { items: [], fallback: null }, missing: { items: [], fallback: null } }
  let mode = null

  for (const line of lines) {
    if (line.includes('Output generated by:')) { continue } // skip header line
    if (line.includes('🔄 Repeats')) { mode = 'repeats'; continue }
    if (line.includes('❌ Missing')) { mode = 'missing'; continue }
    if (line.includes('No repeated stickers available for trade.')) { result.repeats.fallback = line; continue }
    if (line.includes('No missing stickers')) { result.missing.fallback = line; continue }
    const parts = line.split(',')
    if (!parts.length) { continue }
    let icon = null
    let code = null
    const first = parts[0]

    if (includeFlags && first.includes(' ')) {
      const { icon: parsedIcon, code: parsedCode } = parseCodeAndIcon(first, includeFlags)
      icon = parsedIcon
      code = parsedCode
    }
    if (!code) { code = first } // if no icon, first part is code

    const tokens = [] // no transformation, just collect tokens as-is for testing
    for (let i = 1; i < parts.length; i++) {
      const token = parts[i].trim()
      if (token) { tokens.push(token) }
    }
    const entry = { code, icon, tokens }
    if (mode === 'repeats') { result.repeats.items.push(entry) }
    if (mode === 'missing') { result.missing.items.push(entry) }
  }

  return result
}

/**
 * Parses the export format of exportAllData, extracting country codes, optional icons, and sticker/count pairs into structured
 * objects for easier assertions in tests. The parser is designed to handle both compact and non-compact formats,
 * as well as optional flag (icon) inclusion.
 * @param {string} text - Raw exportAllData output string.
 * @param {{ includeFlags?: boolean }} options - Parsing options.
 * @returns {Array<{code:string,icon:string|null,tokens:Array<string>}>} - Parsed lines with country code, optional icon,
 *  and sticker/count tokens.
 */
function parseExportAllData (text, { includeFlags = false } = {}) {
  const lines = text.split('\n').filter(Boolean)
  const result = []
  for (const line of lines) {
    const parts = line.split(',')
    let code = null
    let icon = null
    const first = parts[0]
    if (includeFlags && first.includes(' ')) {
      const { icon: parsedIcon, code: parsedCode } = parseCodeAndIcon(first, includeFlags)
      icon = parsedIcon
      code = parsedCode
    }
    if (!code) { code = first }
    const tokens = []
    for (let i = 1; i < parts.length; i++) {
      const token = parts[i].trim()
      if (token) { tokens.push(token) }
    }
    result.push({ code, icon, tokens })
  }
  return result
}

/**
 * Helper function to build counts array from parser output pairs for easier to populate input values.
 * @param {Array<{sticker:number,count:number}>} pairs - Array of sticker/count objects.
 * @returns {Array<number>} - Array of counts indexed by sticker number.
 */
const buildCounts = (pairs = []) => {
  const counts = Array(21).fill(0)
  for (const pair of pairs) {
    if (!pair) { continue }
    counts[pair.sticker] = pair.count
  }
  return counts
}

/**
 * Computes album completion count from sticker/count pairs.
 * A sticker contributes when count >= 1.
 * @param {Array<{sticker:number,count:number}>} pairs - Array of sticker/count objects.
 * @returns {number}
 */
const computeDone = (pairs = []) => {
  return pairs.filter(pair => pair && pair.count >= 1).length
}

describe('ExportService (unit)', () => {
  const { initTestKernel } = require('./utils/testKernel.js')
  let service
  beforeAll(() => {
    initTestKernel()
    service = new ExportService()
  })

  describe('exportAllStickerData (static)', () => {
    test('returns valid export payload (default options)', () => {
      const result = service.exportAllStickerData({})
      expect(result).toEqual({ success: true, text: expect.any(String), lines: expect.any(Number) })
    })
    test('respects includeFlags=true', () => {
      const result = service.exportAllStickerData({ includeFlags: true })
      expect(result.success).toBe(true)
      expect(typeof result.text).toBe('string')
    })
    test('respects isCompact=true', () => {
      const result = service.exportAllStickerData({ isCompact: true })
      expect(result.success).toBe(true)
      expect(result.text).toContain('FWC') // sanity check only
    })
  })

  describe('exportSharedStickerData (static)', () => {
    test('returns valid shared export payload (default options)', () => {
      const result = service.exportSharedStickerData({})
      expect(result).toEqual({ success: true, text: expect.any(String), lines: expect.any(Number) })
      expect(result.text).toContain('🔄 Repeats')
      expect(result.text).toContain('❌ Missing')
    })
    test('respects sortByDone=true', () => {
      const result = service.exportSharedStickerData({ sortByDone: true })
      expect(result.success).toBe(true)
      expect(result.text).toContain('🔄 Repeats')
    })
    test('respects includeFlags=true and isCompact=true', () => {
      const result = service.exportSharedStickerData({ includeFlags: true, isCompact: true })
      expect(result.success).toBe(true)
      expect(result.text).toContain('❌ Missing')
    })
  })
})

/** ExportStickers (unit) */
describe('ExportStickers (unit)', () => {
  let inputStickers, mexInputStickers
  let mexExportStickers, fwcExportStickers, exportStickers

  /* Define input data and ExportStickers instances before all tests to ensure consistent test conditions
  and avoid redundancy. */
  beforeAll(() => {
    inputStickers = [
      { sticker: 19, count: 1 }, { sticker: 20, count: 2 },
      { sticker: 0, count: 1 }, { sticker: 1, count: 1 }, { sticker: 2, count: 1 }, { sticker: 3, count: 2 },
      { sticker: 4, count: 1 }, { sticker: 5, count: 1 }, { sticker: 6, count: 2 }, { sticker: 8, count: 1 },
      { sticker: 9, count: 3 }, { sticker: 10, count: 3 }, { sticker: 11, count: 3 }
    ]
    mexInputStickers = [...inputStickers, { sticker: 15, count: 1 }] // add sticker 1 for MEX to create a difference with FWC

    // normal: 🏆 FWC,0,1,2,3(2),4,5,6(2),8,9(3),10(3),11(3),19, done = 12
    // compact: 🏆 FWC,0-2,3(2),4-5,6(2),8,9-11(3),19
    const fwcLine = {
      code: 'FWC',
      icon: '🏆',
      done: computeDone(inputStickers),
      counts: buildCounts(inputStickers)
    }
    // normal: 🇲🇽 MEX,1,2,3(2),4,5,6(2),8,9(3),10(3),11(3),15,19,20(2), done = 13
    // compact: 🇲🇽 MEX,1-2,3(2),4-5,6(2),8,9-11(3),15,19,20(2)
    const mexLine = {
      code: 'MEX',
      icon: '🇲🇽',
      done: computeDone(mexInputStickers),
      counts: buildCounts(mexInputStickers)
    }
    fwcExportStickers = new ExportStickers([fwcLine])
    mexExportStickers = new ExportStickers([mexLine])

    // Repeats:
    //   FWC,3,6,9,10,11. Compact: FWC,3,6,9-11
    //   MEX,3,6,8,9,10,11,20. Compact: MEX,3,6,8-11,20
    // Missing:
    //   FWC,7,12,13,14,15,16,17,19,19. Compact: FWC,7,12-19
    //   MEX,7,12,13,14,16,17,18. Compact: MEX,7,12-14,16-18
    exportStickers = new ExportStickers([fwcLine, mexLine])
  })

  /** Tests for exportAllData() method, ensuring correct export behavior and contract adherence. */
  describe('exportAllData()', () => {
    test('exportAllData returns correct contract for MEX, { includeFlags: false, isCompact: false }', () => {
      const result = mexExportStickers.exportAllData({ includeFlags: false, isCompact: false })
      const parsed = parseExportAllData(result.text, { includeFlags: false, isCompact: false })
      expect(parsed[0]).toEqual({
        code: 'MEX',
        icon: null,
        tokens: ['1', '2', '3(2)', '4', '5', '6(2)', '8',
          '9(3)', '10(3)', '11(3)', '15', '19', '20(2)']
      })
    })
    test('exportAllData returns correct contract for MEX, { includeFlags: false, isCompact: true }', () => {
      const result = mexExportStickers.exportAllData({ includeFlags: false, isCompact: true })
      const parsed = parseExportAllData(result.text, { includeFlags: false })
      expect(parsed[0]).toEqual({
        code: 'MEX',
        icon: null,
        tokens: ['1-2', '3(2)', '4-5', '6(2)', '8',
          '9-11(3)', '15', '19', '20(2)']
      })
    })
    test('exportAllData returns correct contract for FWC, { includeFlags: true, isCompact: false }', () => {
      const result = fwcExportStickers.exportAllData({ includeFlags: true, isCompact: false })
      const parsed = parseExportAllData(result.text, { includeFlags: true })
      expect(parsed[0]).toEqual({
        code: 'FWC',
        icon: '🏆',
        tokens: ['0', '1', '2', '3(2)', '4', '5', '6(2)', '8',
          '9(3)', '10(3)', '11(3)', '19']
      })
    })
    test('exportAllData returns correct contract for FWC, { includeFlags: true, isCompact: true }', () => {
      const result = fwcExportStickers.exportAllData({ includeFlags: true, isCompact: true })
      const parsed = parseExportAllData(result.text, { includeFlags: true })
      expect(parsed[0]).toEqual({
        code: 'FWC',
        icon: '🏆',
        tokens: ['0-2', '3(2)', '4-5', '6(2)', '8',
          '9-11(3)', '19']
      })
    })
    test('exportAllData returns correct contract for FWC, MEX, { includeFlags: true, isCompact: false }', () => {
      const result = exportStickers.exportAllData({ includeFlags: true, isCompact: false })
      const parsed = parseExportAllData(result.text, { includeFlags: true })
      expect(parsed[0]).toEqual({
        code: 'FWC',
        icon: '🏆',
        tokens: ['0', '1', '2', '3(2)', '4', '5', '6(2)', '8',
          '9(3)', '10(3)', '11(3)', '19']
      })
      expect(parsed[1]).toEqual({
        code: 'MEX',
        icon: '🇲🇽',
        tokens: ['1', '2', '3(2)', '4', '5', '6(2)', '8',
          '9(3)', '10(3)', '11(3)', '15', '19', '20(2)']
      })
    })
    test('exportAllData returns correct contract with empty dataset', () => {
      const exportStickers = new ExportStickers([{ code: 'FWC', icon: '🏆', done: 0, counts: buildCounts() }])
      const result = exportStickers.exportAllData({ includeFlags: false, isCompact: false })
      expect(result).toEqual(expect.objectContaining({
        success: true,
        text: expect.any(String),
        lines: expect.any(Number)
      }))
      const parsed = parseExportAllData(result.text, { includeFlags: false })
      expect(parsed).toEqual([])
    })
  })

  /**
   * Tests for exportSharedData() method, ensuring correct export behavior, including handling of edge
   * cases such as no repeats or complete albums, as well as contract adherence.
   */
  describe('exportSharedData()', () => {
    test('exportSharedData fallback when no repeats exist', () => {
      const exportStickers = new ExportStickers([
        { code: 'FWC', icon: '🏆', done: computeDone([]), counts: buildCounts([]) },
        { code: 'MEX', icon: '🇲🇽', done: computeDone([]), counts: buildCounts([]) }
      ])
      const result = exportStickers.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.fallback).toBe('No repeated stickers available for trade.')
      expect(parsed.repeats.items).toEqual([])
    })
    test('exportSharedData fallback when album complete', () => {
      const full = Array.from({ length: 21 }, (_, i) => ({ sticker: i, count: 1 }))
      const exportStickers = new ExportStickers([
        { code: 'FWC', icon: '🏆', done: computeDone(full), counts: buildCounts(full) },
        { code: 'MEX', icon: '🇲🇽', done: computeDone(full), counts: buildCounts(full) }
      ])
      const result = exportStickers.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.missing.fallback).toBe('No missing stickers, album complete. Congratulations!')
      expect(parsed.missing.items).toEqual([])
    })
    test('exportSharedData repeats + missing both exist', () => {
      const fwc = [{ sticker: 3, count: 2 }]
      const mex = []
      const exportStickers = new ExportStickers([
        { code: 'FWC', icon: '🏆', done: computeDone(fwc), counts: buildCounts(fwc) },
        { code: 'MEX', icon: '🇲🇽', done: computeDone(mex), counts: buildCounts(mex) }
      ])
      const result = exportStickers.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.items.length).toBeGreaterThan(0)
      expect(parsed.missing.items.length).toBeGreaterThan(0)
    })
    test('exportSharedData correct contract for FWC, MEX, { includeFlags: true, isCompact: false }', () => {
      const exportStickers = new ExportStickers([
        { code: 'FWC', icon: '🏆', done: computeDone([]), counts: buildCounts([]) },
        { code: 'MEX', icon: '🇲🇽', done: computeDone([]), counts: buildCounts([]) }
      ])
      const result = exportStickers.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      expect(result.text.indexOf('🔄 Repeats')).toBeLessThan(result.text.indexOf('❌ Missing'))
    })

    test('exportSharedData contract for FWC, MEX, { includeFlags: false, isCompact: false, sortByDone: false }', () => {
      const result = exportStickers.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: false, sortByDone: false }', () => {
      const result = exportStickers.exportSharedData({ includeFlags: true, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: false, isCompact: false, sortByDone: true }', () => {
      const result = exportStickers.exportSharedData({ includeFlags: false, sortByDone: true, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: null, tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: null, tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: false, sortByDone: true }', () => {
      const result = exportStickers.exportSharedData({ includeFlags: true, sortByDone: true, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: false, isCompact: false, sortByDone: true }', () => {
      const result = exportStickers.exportSharedData({ includeFlags: false, sortByDone: true, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: null, tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: null, tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: true, sortByDone: false }', () => {
      const result = exportStickers.exportSharedData({ includeFlags: true, sortByDone: false, isCompact: true })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['3', '6', '9-11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['3', '6', '9-11', '20'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['7', '12-18'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['7', '12-14', '16-18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: true, sortByDone: true }', () => {
      const result = exportStickers.exportSharedData({ includeFlags: true, sortByDone: true, isCompact: true })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['3', '6', '9-11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['3', '6', '9-11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['7', '12-18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['7', '12-14', '16-18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: true, sortByDone: true }', () => {
      const result = exportStickers.exportSharedData({ includeFlags: false, sortByDone: true, isCompact: true })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['3', '6', '9-11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['3', '6', '9-11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: null, tokens: ['7', '12-18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: null, tokens: ['7', '12-14', '16-18'] })
    })
  })
})
