// @ts-nocheck
// test/ImportExportService.unit.test.js
/**
 * Unit tests for ImportExportService.
 *
 * Focus:
 * - import parsing behavior
 * - validation rules
 * - export structure stability
 *
 * All Google Apps Script dependencies are mocked via: initTestKernel in text/utils/testKernel.js,
 * which sets up the necessary environment for testing without actual GAS services.
 */

/* global __writeRangeMock, __countsRange */

const { initTestKernel } = require('./utils/testKernel.js')
// eslint-disable-next-line
const { ImportExportService, ImportService, ExportService, InputLineNormalize } = require('../build/ImportExportService.js')

/** Helper method to be used in both parsers */
function parseCodeAndIcon (first, includeFlags) {
  if (!includeFlags || !first.includes(' ')) {
    return { code: first, icon: null }
  }
  const split = first.trim().split(/\s+/)
  return { icon: split[0], code: split.slice(1).join(' ') }
}

/**
 * Parses exportSharedData output into structured testable object.
 * Supports compact and non-compact formats and optional flag (icon) inclusion.
 *
 * @param {string} text - Raw exportSharedData output string.
 * @param {{ isCompact?: boolean, includeFlags?: boolean }} options - Parsing options.
 * @return {{ repeats: { items: Array<{code:string,icon:string,tokens:Array<string>}>, fallback: string|null },
 *  missing: { items: Array<{code:string,icon:string,tokens:Array<string>}>, fallback: string|null } }}
 *  Parsed data structure with repeats and missing sections.
 */
function parseExportSharedData (text, { includeFlags = false } = {}) {
  const lines = text.split('\n').filter(Boolean)
  const result = { repeats: { items: [], fallback: null }, missing: { items: [], fallback: null } }
  let mode = null

  for (const line of lines) {
    if (line.includes('Output generated by:')) { continue } // skip header line
    if (line.includes('🔄 Repeats')) { mode = 'repeats'; continue }
    if (line.includes('❌ Missing')) { mode = 'missing'; continue }
    if (line.includes('No repeated stickers available for trade.')) { result.repeats.fallback = line; continue }
    if (line.includes('No missing stickers')) { result.missing.fallback = line; continue }
    const parts = line.split(',')
    if (!parts.length) { continue }
    let icon = null
    let code = null
    const first = parts[0]

    if (includeFlags && first.includes(' ')) {
      const { icon: parsedIcon, code: parsedCode } = parseCodeAndIcon(first, includeFlags)
      icon = parsedIcon
      code = parsedCode
    }
    if (!code) { code = first } // if no icon, first part is code

    const tokens = [] // no transformation, just collect tokens as-is for testing
    for (let i = 1; i < parts.length; i++) {
      const token = parts[i].trim()
      if (token) { tokens.push(token) }
    }
    const entry = { code, icon, tokens }
    if (mode === 'repeats') { result.repeats.items.push(entry) }
    if (mode === 'missing') { result.missing.items.push(entry) }
  }

  return result
}

/**
 * Parses the export format of exportAllData, extracting country codes, optional icons, and sticker/count pairs into structured
 * objects for easier assertions in tests. The parser is designed to handle both compact and non-compact formats,
 * as well as optional flag (icon) inclusion.
 * @param {string} text - Raw exportAllData output string.
 * @param {{ includeFlags?: boolean }} options - Parsing options.
 * @returns {Array<{code:string,icon:string|null,tokens:Array<string>}>} - Parsed lines with country code, optional icon,
 *  and sticker/count tokens.
 */
function parseExportAllData (text, { includeFlags = false } = {}) {
  const lines = text.split('\n').filter(Boolean)
  const result = []
  for (const line of lines) {
    const parts = line.split(',')
    let code = null
    let icon = null
    const first = parts[0]
    if (includeFlags && first.includes(' ')) {
      const { icon: parsedIcon, code: parsedCode } = parseCodeAndIcon(first, includeFlags)
      icon = parsedIcon
      code = parsedCode
    }
    if (!code) { code = first }
    const tokens = []
    for (let i = 1; i < parts.length; i++) {
      const token = parts[i].trim()
      if (token) { tokens.push(token) }
    }
    result.push({ code, icon, tokens })
  }
  return result
}

/**
 * Helper function to build counts array from parser output pairs for easier to populate input values.
 * @param {Array<{sticker:number,count:number}>} pairs - Array of sticker/count objects.
 * @returns {Array<number>} - Array of counts indexed by sticker number.
 */
const buildCounts = (pairs = []) => {
  const counts = Array(21).fill(0)
  for (const pair of pairs) {
    if (!pair) { continue }
    counts[pair.sticker] = pair.count
  }
  return counts
}

/**
 * Computes album completion count from sticker/count pairs.
 * A sticker contributes when count >= 1.
 * @param {Array<{sticker:number,count:number}>} pairs - Array of sticker/count objects.
 * @returns {number}
 */
const computeDone = (pairs = []) => {
  return pairs.filter(pair => pair && pair.count >= 1).length
}

/** ImportExportService (unit) */
describe('ImportExportService (unit)', () => {
  /* Each test starts with cleared mocks to ensure isolation and prevent state leakage between tests.
  ImportExport Service has GAS dependency so we need mock objects for SpreadsheetApp and other services.
  created in via initTestKernel() */
  beforeEach(() => {
    jest.clearAllMocks()
    initTestKernel()
  })

  /**
   Tests for import() method covering successful parsing and import scenarios, including handling
  of multiple countries and different import modes, as well as validation of error handling for invalid modes.
  */
  describe('import() modes', () => {
    test('clean_all clears sheet before import', () => {
      const service = new ImportExportService()
      const result = service.import('FWC,1,2', 'clean_all')
      expect(result.success).toBe(true)
      expect(result.message).toContain('1 country row')
    })
    test('replace_countries clears only target countries', () => {
      const service = new ImportExportService()
      const result = service.import('FWC,1,2', 'replace_countries')
      expect(result.success).toBe(true)
      expect(result.message).toMatch(/Imported \d+ country row\(s\) successfully\./)
    })
    test('invalid mode throws', () => {
      const service = new ImportExportService()
      expect(() => service.import('FWC,1', 'invalid')).toThrow(/Invalid import mode/)
    })
  })

  /** Tests for import() core behavior, focusing on the parsing and importing logic for different input formats. */
  describe('import() core behavior', () => {
    test('parses and imports single country', () => {
      const service = new ImportExportService()
      const result = service.import('FWC,1,2,3')
      expect(result).toEqual(expect.objectContaining({
        success: true,
        message: expect.any(String),
        warnings: expect.any(Array)
      }))
      expect(result.message).toMatch(/Imported 1 country/)
    })
    test('handles multiple countries correctly', () => {
      const service = new ImportExportService()
      const result = service.import('FWC,1\nMEX,2,3')
      expect(result.success).toBe(true)
      expect(result.message).toMatch(/Imported 2 country/)
    })
  })

  /** Tests for parser integration, ensuring that the import and export methods correctly interact with the parser. */
  describe('parser integration', () => {
    test('warnings are preserved from parser', () => {
      const service = new ImportExportService()
      const result = service.import('🇺🇸,1')
      expect(result.success).toBe(true)
      expect(Array.isArray(result.warnings)).toBe(true)
      expect(result.warnings[0]).toMatch(/country/i)
    })
  })

  /**
   * Tests for contract stability, confirming that the import and export methods always return objects
   * with the expected properties.
   */
  describe('contract stability', () => {
    test('import returns stable shape', () => {
      const service = new ImportExportService()
      const result = service.import('FWC,1')
      expect(Object.keys(result).sort()).toEqual(['message', 'success', 'warnings'])
    })
    test('export returns stable shape', () => {
      const result = ImportExportService.exportStickerData({ includeFlags: false })
      expect(Object.keys(result).sort()).toEqual(['lines', 'success', 'text'])
    })
  })

  /** Tests for preview() method, ensuring correct preview behavior and contract adherence. */
  describe('preview()', () => {
    test('returns preview payload without writing data', () => {
      const service = new ImportExportService()
      const result = service.preview('FWC,1,2,3')
      expect(result.success).toBe(true)
      expect(Array.isArray(result.countries)).toBe(true)
      expect(Array.isArray(result.warnings)).toBe(true)
      expect(result.countries.length).toBe(1)
      expect(result.countries[0].code).toBe('FWC')
    })
    test('preview forwards parser warnings to the caller', () => {
      const service = new ImportExportService()
      const result = service.preview('MEX,1,22') // sticker 22 out of range → warning
      expect(result.success).toBe(true)
      expect(result.warnings.some(w => w.includes('22'))).toBe(true)
    })
  })

  /**
   * Tests for sheet writing behavior, confirming that the import method correctly interacts
   * with the sheet to update sticker counts.
   */
  describe('sheet writes', () => {
    test('writes correct sticker matrix to sheet', () => {
      const service = new ImportExportService()
      service.import('FWC,1,3(2)')
      // Assert: values written to sheet
      expect(global.__writeRangeMock.setValues).toHaveBeenCalled()
      expect(global.__getRangeMock).toHaveBeenCalledTimes(1)
      const written = global.__writeRangeMock.setValues.mock.calls[0][0]
      // THIS is the real "cell content" assertion
      expect(written[0][1]).toBe(1)
      expect(written[0][3]).toBe(2)
      // Assert no other cells were written to
      const [row] = global.__getRangeMock.mock.calls[0]
      expect(row).toBe(1) // row 1 is the first row of counts
    })
    test('exports deterministic formatted sticker string', () => {
      const result = ImportExportService.exportStickerData({ includeFlags: true })
      expect(result.text).toContain('🏆')
      expect(result.text).toContain('FWC')
      expect(result.text).toContain('1')
      expect(result.text).toContain('3(2)')
    })
    test('export contains no zero values', () => {
      const result = ImportExportService.exportStickerData({ includeFlags: false })
      expect(result.text).not.toMatch(/0\(/)
    })
    test('update mode preserves existing valid sticker values not in the import payload', () => {
      const existingRow = Array(21).fill(0)
      existingRow[3] = 2
      __writeRangeMock.getValues.mockReturnValueOnce([existingRow])
      const service = new ImportExportService()
      service.import('FWC,1', 'update')
      const written = __writeRangeMock.setValues.mock.calls[0][0][0]
      expect(written[1]).toBe(1)
      expect(written[3]).toBe(2)
    })
  })

  /** Tests for sheet clearing behavior, ensuring that the appropriate ranges are cleared based on the import mode. */
  describe('sheet clearing', () => {
    test('clean_all clears counts range', () => {
      const service = new ImportExportService()
      service.import('FWC,1', 'clean_all')
      expect(__countsRange.clearContent).toHaveBeenCalledTimes(1)
    })
    test('replace_countries clears target row before writing', () => {
      const service = new ImportExportService()
      service.import('FWC,1', 'replace_countries')
      expect(__writeRangeMock.clearContent).toHaveBeenCalledTimes(1)
    })
    test('replace_countries clears before writing', () => {
      const service = new ImportExportService()
      service.import('FWC,1,3(2)', 'replace_countries')
      const clearCallIndex = __writeRangeMock.clearContent.mock.invocationCallOrder[0]
      const writeCallIndex = __writeRangeMock.setValues.mock.invocationCallOrder[0]
      expect(clearCallIndex).toBeLessThan(writeCallIndex)
    })
  })

  /** Tests that non-valid sticker positions are always written as 0 on import, for all modes. */
  describe('non-valid sticker position zeroing', () => {
    test('FWC import always writes 0 at offset 20 (update mode)', () => {
      const service = new ImportExportService()
      service.import('FWC,1,3(2)')
      const written = __writeRangeMock.setValues.mock.calls[0][0][0]
      expect(written[20]).toBe(0) // offset 20 is non-valid for FWC
    })
    test('non-FWC import always writes 0 at offset 0 (update mode)', () => {
      const service = new ImportExportService()
      service.import('MEX,1,3(2)')
      const written = __writeRangeMock.setValues.mock.calls[0][0][0]
      expect(written[0]).toBe(0) // offset 0 is non-valid for non-FWC
    })
    test('replace_countries mode also zeroes non-valid offset', () => {
      const service = new ImportExportService()
      service.import('MEX,1', 'replace_countries')
      const written = __writeRangeMock.setValues.mock.calls[0][0][0]
      expect(written[0]).toBe(0)
    })
    test('clean_all mode also zeroes non-valid offset', () => {
      const service = new ImportExportService()
      service.import('MEX,1', 'clean_all')
      const written = __writeRangeMock.setValues.mock.calls[0][0][0]
      expect(written[0]).toBe(0)
    })
  })
})

/** ExportService (unit) */
describe('ExportService (unit)', () => {
  let inputStickers, mexInputStickers
  let mexExportService, fwcExportService, exportService

  /* Define input data and ExportService instances before all tests to ensure consistent test conditions
  and avoid redundancy. */
  beforeAll(() => {
    inputStickers = [
      { sticker: 19, count: 1 }, { sticker: 20, count: 2 },
      { sticker: 0, count: 1 }, { sticker: 1, count: 1 }, { sticker: 2, count: 1 }, { sticker: 3, count: 2 },
      { sticker: 4, count: 1 }, { sticker: 5, count: 1 }, { sticker: 6, count: 2 }, { sticker: 8, count: 1 },
      { sticker: 9, count: 3 }, { sticker: 10, count: 3 }, { sticker: 11, count: 3 }
    ]
    mexInputStickers = [...inputStickers, { sticker: 15, count: 1 }] // add sticker 1 for MEX to create a difference with FWC

    // normal: 🏆 FWC,0,1,2,3(2),4,5,6(2),8,9(3),10(3),11(3),19, done = 12
    // compact: 🏆 FWC,0-2,3(2),4-5,6(2),8,9-11(3),19
    const fwcLine = {
      code: 'FWC',
      icon: '🏆',
      done: computeDone(inputStickers),
      counts: buildCounts(inputStickers)
    }
    // normal: 🇲🇽 MEX,1,2,3(2),4,5,6(2),8,9(3),10(3),11(3),15,19,20(2), done = 13
    // compact: 🇲🇽 MEX,1-2,3(2),4-5,6(2),8,9-11(3),15,19,20(2)
    const mexLine = {
      code: 'MEX',
      icon: '🇲🇽',
      done: computeDone(mexInputStickers),
      counts: buildCounts(mexInputStickers)
    }
    fwcExportService = new ExportService([fwcLine])
    mexExportService = new ExportService([mexLine])

    // Repeats:
    //   FWC,3,6,9,10,11. Compact: FWC,3,6,9-11
    //   MEX,3,6,8,9,10,11,20. Compact: MEX,3,6,8-11,20
    // Missing:
    //   FWC,7,12,13,14,15,16,17,19,19. Compact: FWC,7,12-19
    //   MEX,7,12,13,14,16,17,18. Compact: MEX,7,12-14,16-18
    exportService = new ExportService([fwcLine, mexLine])
  })

  /** Tests for exportAllData() method, ensuring correct export behavior and contract adherence. */
  describe('exportAllData()', () => {
    test('exportAllData returns correct contract for MEX, { includeFlags: false, isCompact: false }', () => {
      const result = mexExportService.exportAllData({ includeFlags: false, isCompact: false })
      const parsed = parseExportAllData(result.text, { includeFlags: false, isCompact: false })
      expect(parsed[0]).toEqual({
        code: 'MEX',
        icon: null,
        tokens: ['1', '2', '3(2)', '4', '5', '6(2)', '8',
          '9(3)', '10(3)', '11(3)', '15', '19', '20(2)']
      })
    })
    test('exportAllData returns correct contract for MEX, { includeFlags: false, isCompact: true }', () => {
      const result = mexExportService.exportAllData({ includeFlags: false, isCompact: true })
      const parsed = parseExportAllData(result.text, { includeFlags: false })
      expect(parsed[0]).toEqual({
        code: 'MEX',
        icon: null,
        tokens: ['1-2', '3(2)', '4-5', '6(2)', '8',
          '9-11(3)', '15', '19', '20(2)']
      })
    })
    test('exportAllData returns correct contract for FWC, { includeFlags: true, isCompact: false }', () => {
      const result = fwcExportService.exportAllData({ includeFlags: true, isCompact: false })
      const parsed = parseExportAllData(result.text, { includeFlags: true })
      expect(parsed[0]).toEqual({
        code: 'FWC',
        icon: '🏆',
        tokens: ['0', '1', '2', '3(2)', '4', '5', '6(2)', '8',
          '9(3)', '10(3)', '11(3)', '19']
      })
    })
    test('exportAllData returns correct contract for FWC, { includeFlags: true, isCompact: true }', () => {
      const result = fwcExportService.exportAllData({ includeFlags: true, isCompact: true })
      const parsed = parseExportAllData(result.text, { includeFlags: true })
      expect(parsed[0]).toEqual({
        code: 'FWC',
        icon: '🏆',
        tokens: ['0-2', '3(2)', '4-5', '6(2)', '8',
          '9-11(3)', '19']
      })
    })
    test('exportAllData returns correct contract for FWC, MEX, { includeFlags: true, isCompact: false }', () => {
      const result = exportService.exportAllData({ includeFlags: true, isCompact: false })
      const parsed = parseExportAllData(result.text, { includeFlags: true })
      expect(parsed[0]).toEqual({
        code: 'FWC',
        icon: '🏆',
        tokens: ['0', '1', '2', '3(2)', '4', '5', '6(2)', '8',
          '9(3)', '10(3)', '11(3)', '19']
      })
      expect(parsed[1]).toEqual({
        code: 'MEX',
        icon: '🇲🇽',
        tokens: ['1', '2', '3(2)', '4', '5', '6(2)', '8',
          '9(3)', '10(3)', '11(3)', '15', '19', '20(2)']
      })
    })
    test('exportAllData returns correct contract with empty dataset', () => {
      const service = new ExportService([{ code: 'FWC', icon: '🏆', done: 0, counts: buildCounts() }])
      const result = service.exportAllData({ includeFlags: false, isCompact: false })
      expect(result).toEqual(expect.objectContaining({
        success: true,
        text: expect.any(String),
        lines: expect.any(Number)
      }))
      const parsed = parseExportAllData(result.text, { includeFlags: false })
      expect(parsed).toEqual([])
    })
  })

  /**
   * Tests for exportSharedData() method, ensuring correct export behavior, including handling of edge
   * cases such as no repeats or complete albums, as well as contract adherence.
   */
  describe('exportSharedData()', () => {
    test('exportSharedData fallback when no repeats exist', () => {
      const service = new ExportService([
        { code: 'FWC', icon: '🏆', done: computeDone([]), counts: buildCounts([]) },
        { code: 'MEX', icon: '🇲🇽', done: computeDone([]), counts: buildCounts([]) }
      ])
      const result = service.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.fallback).toBe('No repeated stickers available for trade.')
      expect(parsed.repeats.items).toEqual([])
    })
    test('exportSharedData fallback when album complete', () => {
      const full = Array.from({ length: 21 }, (_, i) => ({ sticker: i, count: 1 }))
      const service = new ExportService([
        { code: 'FWC', icon: '🏆', done: computeDone(full), counts: buildCounts(full) },
        { code: 'MEX', icon: '🇲🇽', done: computeDone(full), counts: buildCounts(full) }
      ])
      const result = service.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.missing.fallback).toBe('No missing stickers, album complete. Congratulations!')
      expect(parsed.missing.items).toEqual([])
    })
    test('exportSharedData repeats + missing both exist', () => {
      const fwc = [{ sticker: 3, count: 2 }]
      const mex = []
      const service = new ExportService([
        { code: 'FWC', icon: '🏆', done: computeDone(fwc), counts: buildCounts(fwc) },
        { code: 'MEX', icon: '🇲🇽', done: computeDone(mex), counts: buildCounts(mex) }
      ])
      const result = service.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.items.length).toBeGreaterThan(0)
      expect(parsed.missing.items.length).toBeGreaterThan(0)
    })
    test('exportSharedData correct contract for FWC, MEX, { includeFlags: true, isCompact: false }', () => {
      const service = new ExportService([
        { code: 'FWC', icon: '🏆', done: computeDone([]), counts: buildCounts([]) },
        { code: 'MEX', icon: '🇲🇽', done: computeDone([]), counts: buildCounts([]) }
      ])
      const result = service.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      expect(result.text.indexOf('🔄 Repeats')).toBeLessThan(result.text.indexOf('❌ Missing'))
    })

    test('exportSharedData contract for FWC, MEX, { includeFlags: false, isCompact: false, sortByDone: false }', () => {
      const result = exportService.exportSharedData({ includeFlags: false, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: false, sortByDone: false }', () => {
      const result = exportService.exportSharedData({ includeFlags: true, sortByDone: false, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: false, isCompact: false, sortByDone: true }', () => {
      const result = exportService.exportSharedData({ includeFlags: false, sortByDone: true, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: null, tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: null, tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: false, sortByDone: true }', () => {
      const result = exportService.exportSharedData({ includeFlags: true, sortByDone: true, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: false, isCompact: false, sortByDone: true }', () => {
      const result = exportService.exportSharedData({ includeFlags: false, sortByDone: true, isCompact: false })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['3', '6', '9', '10', '11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['3', '6', '9', '10', '11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: null, tokens: ['7', '12', '13', '14', '15', '16', '17', '18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: null, tokens: ['7', '12', '13', '14', '16', '17', '18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: true, sortByDone: false }', () => {
      const result = exportService.exportSharedData({ includeFlags: true, sortByDone: false, isCompact: true })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['3', '6', '9-11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['3', '6', '9-11', '20'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['7', '12-18'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['7', '12-14', '16-18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: true, sortByDone: true }', () => {
      const result = exportService.exportSharedData({ includeFlags: true, sortByDone: true, isCompact: true })
      const parsed = parseExportSharedData(result.text, { includeFlags: true })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['3', '6', '9-11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['3', '6', '9-11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: '🏆', tokens: ['7', '12-18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: '🇲🇽', tokens: ['7', '12-14', '16-18'] })
    })
    test('exportSharedData contract for FWC, MEX, { includeFlags: true, isCompact: true, sortByDone: true }', () => {
      const result = exportService.exportSharedData({ includeFlags: false, sortByDone: true, isCompact: true })
      const parsed = parseExportSharedData(result.text, { includeFlags: false })
      expect(parsed.repeats.items[0]).toEqual({ code: 'FWC', icon: null, tokens: ['3', '6', '9-11'] })
      expect(parsed.repeats.items[1]).toEqual({ code: 'MEX', icon: null, tokens: ['3', '6', '9-11', '20'] })
      expect(parsed.missing.items[1]).toEqual({ code: 'FWC', icon: null, tokens: ['7', '12-18'] })
      expect(parsed.missing.items[0]).toEqual({ code: 'MEX', icon: null, tokens: ['7', '12-14', '16-18'] })
    })
  })
})

/** ImportService (unit) */
describe('ImportService (unit)', () => {
  let parser

  /* Each test starts with a fresh instance of ImportService and cleared mocks to ensure
  isolation and prevent state leakage between tests. */
  beforeEach(() => {
    jest.clearAllMocks()
    parser = new ImportService({ FWC: true, MEX: true })
  })

  /**
   Tests for parse() method covering both successful parsing scenarios and expected error cases,as
  well as validation of output structure and warning generation.
  */
  describe('parse() success paths', () => {
    test('simple parsing returns correct structure', () => {
      const result = parser.parse('FWC,1,2,3')
      expect(result.countries[0].code).toBe('FWC')
      expect(result.countries[0].counts).toEqual({ 1: 1, 2: 1, 3: 1 })
      expect(result.warnings.length).toBe(0)
    })
    test('repeat syntax expands correctly', () => {
      const result = parser.parse('FWC,2(2),5(3)')
      expect(result.countries[0].counts).toEqual({ 2: 2, 5: 3 })
    })
    test('range syntax works', () => {
      const result = parser.parse('FWC,1-5')
      expect(result.countries[0].counts).toEqual({ 1: 1, 2: 1, 3: 1, 4: 1, 5: 1 })
    })
    test('mixed ranges are accepted', () => {
      const result = parser.parse('MEX,1-3,18-20')
      expect(result.countries[0].counts).toEqual({ 1: 1, 2: 1, 3: 1, 18: 1, 19: 1, 20: 1 })
    })
  })

  /**
   Tests for error handling in parse() method, ensuring that invalid inputs are properly
  rejected with exceptions, and that edge cases like empty input are handled gracefully.
  */
  describe('parse() error cases', () => {
    test('reject empty input with message', () => {
      expect(() => parser.parse('')).toThrow('No input provided')
    })
    test('unknown country produces warning and skips line', () => {
      const result = parser.parse('🇺🇸,1')
      expect(result.countries.length).toBe(0)
      expect(result.warnings.length).toBeGreaterThan(0)
      expect(result.warnings[0]).toMatch(/country/i)
    })
    test('unknown country code produces warning for BRA', () => {
      const result = parser.parse('BRA,25')
      expect(result.countries.length).toBe(0)
      expect(result.warnings.length).toBeGreaterThan(0)
    })
    test('out-of-range sticker produces warning and is skipped, not an error', () => {
      const result = parser.parse('MEX,1,22')
      expect(result.countries.length).toBe(1) // line is still imported; sticker 22 is skipped
      expect(result.warnings.some(w => w.includes('22') && w.includes('outside allowed range'))).toBe(true)
    })
  })

  /**
   Tests for validation behavior in parse() method, verifying that warnings are generated for issues
  like duplicate stickers, and that the output structure includes expected properties like warnings array
   and preserved country code.
   */
  describe('behavior validation', () => {
    test('returns warnings array always defined', () => {
      const result = parser.parse('FWC,1,2,3')
      expect(Array.isArray(result.warnings)).toBe(true)
    })
    test('country code is preserved in output', () => {
      const result = parser.parse('FWC,1,2,3')
      expect(result.countries[0].code).toBe('FWC')
    })
  })

  /**
   Tests for handling of duplicate country entries in parse() method, ensuring that the first occurrence
  is used and subsequent duplicates are ignored with appropriate warnings.
  */
  describe('duplicate country handling', () => {
    test('first country occurrence wins and second is ignored', () => {
      const result = parser.parse('FWC,1,2\nFWC,3,4')
      expect(result.countries.length).toBe(1)
      expect(result.countries[0].code).toBe('FWC')
      expect(result.countries[0].counts).toEqual({ 1: 1, 2: 1 })
      expect(result.warnings.some(w => w.includes('duplicate country'))).toBe(true)
    })
  })

  /**
   Tests for aggregation of multiple warnings in parse() method, confirming that all issues are
  collected and reported together rather than just the first one encountered.
  */
  describe('warning aggregation', () => {
    test('collects multiple warnings in a single parse', () => {
      const result = parser.parse('FWC,1,1\n🇺🇸,1\nBRA,25')
      expect(result.warnings.length).toBeGreaterThan(1)
      expect(result.countries.length).toBeLessThanOrEqual(1)
    })
  })
})

/** InputLineNormalizer (unit) */
describe('InputLineNormalize (unit)', () => {
  let normalize

  beforeEach(() => {
    jest.clearAllMocks()
    normalize = new InputLineNormalize({ FWC: true, MEX: true, BRA: true, CPV: true })
  })

  /* Tests for normalizeLine() method covering a wide range of input formats and edge cases, ensuring that
  the normalization process correctly handles various token formats, delimiters, whitespace, and invalid inputs,
  while producing consistent output and appropriate warnings. */
  describe('normalizeLine()', () => {
    test('Format 2 mixed tokens are normalized to Format 1 canonical output', () => {
      const result = normalize.normalizeLine('🇲🇽 MEX-1;MEX3-5(2);MEX-7')
      expect(result.line).toBe('MEX,1,3(2),4(2),5(2),7')
    })
    test('semicolon delimiter is normalized to comma and parsed correctly', () => {
      const result = normalize.normalizeLine('BRA-1;BRA-2;BRA-3')
      expect(result.line).toBe('BRA,1,2,3')
    })
    test('mix lower and upper case country code and parsed correctly', () => {
      const result = normalize.normalizeLine('Bra-1;BRA-2;bra-3')
      expect(result.line).toBe('BRA,1,2,3')
    })
    test('normalize repeats NxX is applied correctly', () => {
      const result = normalize.normalizeLine('MEX,1,2x2,3')
      expect(result.line).toBe('MEX,1,2(2),3')
    })
    test('normalize repeats N(xX) is applied correctly', () => {
      const result = normalize.normalizeLine('MEX-1,MEX-2(x2),MEX3')
      expect(result.line).toBe('MEX,1,2(2),3')
    })
    test('normalize repeats A-BxX is applied correctly', () => {
      const result = normalize.normalizeLine('MEX,1,4-6x2,10')
      expect(result.line).toBe('MEX,1,4(2),5(2),6(2),10')
    })
    test('normalize repeats A-B(xX) is applied correctly', () => {
      const result = normalize.normalizeLine('MEX,1,4-6(x2),10')
      expect(result.line).toBe('MEX,1,4(2),5(2),6(2),10')
    })
    test('Format 2 without dash is parsed correctly', () => {
      const result = normalize.normalizeLine('MEX1,MEX2,MEX3')
      expect(result.line).toBe('MEX,1,2,3')
    })
    test('range expansion without repeats is fully expanded', () => {
      const result = normalize.normalizeLine('CPV-1-3')
      expect(result.line).toBe('CPV,1,2,3')
    })
    test('range expansion with repeats is applied per sticker', () => {
      const result = normalize.normalizeLine('CPV-1-3(2)')
      expect(result.line).toBe('CPV,1(2),2(2),3(2)')
    })
    test('mixed Format 1 and Format 2 tokens are normalized together', () => {
      const result = normalize.normalizeLine('MEX-1,MEX2,MEX3-4(2)')
      expect(result.line).toBe('MEX,1,2,3(2),4(2)')
    })
    test('whitespace and emoji are stripped before parsing', () => {
      const result = normalize.normalizeLine('🇧🇷   BRA-1 , BRA2 ; BRA-3')
      expect(result.line).toBe('BRA,1,2,3')
    })
    test('invalid country code returns null line', () => {
      const result = normalize.normalizeLine('XXX-1,2,3')
      expect(result.line).toBeNull()
    })
    test('multiple exclusion operators <>^', () => {
      const result = normalize.normalizeLine('<>^MEX,1,2')
      expect(result.line).toBe('MEX,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20')
    })
    test('multiple exclusion operators !=^<><>!=', () => {
      const result = normalize.normalizeLine('!=^<><>!=MEX,1,2')
      expect(result.line).toBe('MEX,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20')
    })
    test('exclusion operator <> computes complement for non-FWC country', () => {
      const result = normalize.normalizeLine('<>MEX,1,2')
      expect(result.line).toBe('MEX,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20')
    })
    test('exclusion operator != behaves same as <>', () => {
      const result = normalize.normalizeLine('!=MEX,1,2')
      expect(result.line).toBe('MEX,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20')
    })
    test('exclusion operator ^ applies complement correctly', () => {
      const result = normalize.normalizeLine('^MEX,1,2')
      expect(result.line).toBe('MEX,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20')
    })
    test('FWC exclusion operator includes 0..19 valid positions only', () => {
      const result = normalize.normalizeLine('<>FWC,1-10')
      expect(result.line).toBe('FWC,0,11,12,13,14,15,16,17,18,19')
    })
    test('duplicate tokens are deduplicated using first-occurrence rule', () => {
      const result = normalize.normalizeLine('MEX,1,1,2,2')
      expect(result.line).toBe('MEX,1,2')
    })
    test('overlapping ranges are deduplicated using first occurrence wins', () => {
      const result = normalize.normalizeLine('MEX,1-3,3-5')
      expect(result.line).toBe('MEX,1,2,3,4,5')
    })
    test('empty input returns null', () => {
      const result = normalize.normalizeLine('')
      expect(result.line).toBeNull()
    })
    test('Format 2 token with repeat preserves count after expansion', () => {
      const result = normalize.normalizeLine('MEX3(2),MEX4')
      expect(result.line).toBe('MEX,3(2),4')
    })
    test('Format 2 mixed separators and repeated delimiters are normalized', () => {
      const result = normalize.normalizeLine('MEX-1,,;MEX2;;;MEX3')
      expect(result.line).toBe('MEX,1,2,3')
    })
    test('range with repeats and overlap deduplicates correctly', () => {
      const result = normalize.normalizeLine('MEX-1-3(2),MEX2')
      expect(result.line).toBe('MEX,1(2),2(2),3(2)')
    })
    test('adjacent ranges merge logically without duplication', () => {
      const result = normalize.normalizeLine('MEX-1-2,MEX2-3')
      expect(result.line).toBe('MEX,1,2,3')
    })
    test('first occurrence wins for mixed count formats', () => {
      const result = normalize.normalizeLine('MEX,1(2),1,1(3)')
      expect(result.line).toBe('MEX,1(2)')
    })
    test('dedup respects expansion order not input order', () => {
      const result = normalize.normalizeLine('MEX-1-2,MEX1')
      expect(result.line).toBe('MEX,1,2')
    })
    test('exclusion ignores repeated tokens but still computes complement', () => {
      const result = normalize.normalizeLine('<>MEX,1(2),2(3)')
      expect(result.line).toBe('MEX,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20')
    })
    test('FWC exclusion ignores repeats and expands correctly', () => {
      const result = normalize.normalizeLine('<>FWC,1(2),2(3)')
      expect(result.line).toBe('FWC,0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19')
    })
    test('completely invalid tokens produce null output', () => {
      const result = normalize.normalizeLine('!!!@@@###')
      expect(result.line).toBeNull()
    })
    test('mixed valid and invalid tokens still produce valid output', () => {
      const result = normalize.normalizeLine('MEX-1,@@@,MEX2')
      expect(result.line).toBe('MEX,1,2')
    })
    test('tokens from different country are ignored but do not break line', () => {
      const result = normalize.normalizeLine('MEX-1,ARG-2,MEX3')
      expect(result.line).toBe('MEX,1,3')
    })
    test('output order is stable regardless of input ordering', () => {
      const result = normalize.normalizeLine('MEX3,MEX1,MEX2')
      expect(result.line).toBe('MEX,1,2,3')
    })
    test('repeat counts in exclusion line do not produce a warning', () => {
      const result = normalize.normalizeLine('<>MEX,1-3(2)')
      expect(result.warnings.length).toBe(0) // repeats silently ignored in exclusion per spec
      expect(result.line).not.toBeNull()
    })
  })
  describe('normalizeLine() warnings and errors', () => {
    test('invalid country returns warning', () => {
      const result = normalize.normalizeLine('XXX-1,2,3')
      expect(result.line).toBeNull()
      expect(result.warnings).toEqual(['Country "XXX": not valid, line skipped.'])
    })
    test('mixed country tokens are skipped with warning', () => {
      const result = normalize.normalizeLine('MEX-1,ARG-2,MEX-3')
      expect(result.line).toBe('MEX,1,3')
      expect(result.warnings).toContain(
        'Country "MEX": "ARG-2" skipped. All stickers in the line should belong to the same country.'
      )
    })
    test('duplicate sticker emits warning', () => {
      const result = normalize.normalizeLine('MEX,1,1')
      expect(result.line).toBe('MEX,1')
      expect(result.warnings).toContain('Country "MEX": duplicate sticker(s) "1" ignored; first occurrence wins.')
    })
    test('duplicate sticker with different counts emits warning', () => {
      const result = normalize.normalizeLine('MEX,1(2),1(3)')
      expect(result.line).toBe('MEX,1(2)')
      expect(result.warnings).toContain('Country "MEX": duplicate sticker(s) "1" ignored; first occurrence wins.')
    })
    test('duplicate generated by range expansion emits warning', () => {
      const result = normalize.normalizeLine('MEX,1-3,3-5')
      expect(result.line).toBe('MEX,1,2,3,4,5')
      expect(result.warnings).toContain('Country "MEX": duplicate sticker(s) "3" ignored; first occurrence wins.')
    })
    test('duplicate stickers inside exclusion emit warning', () => {
      const result = normalize.normalizeLine('<>MEX,1,1,2')
      expect(result.line).toBe('MEX,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20')
      expect(result.warnings).toContain('Country "MEX": duplicate sticker(s) "1" ignored; first occurrence wins.')
    })
    test('duplicate stickers due to range overlap in exclusion emit warning', () => {
      const result = normalize.normalizeLine('<>MEX,1-10,8-15')
      expect(result.line).toBe('MEX,16,17,18,19,20')
      expect(result.warnings).toContain('Country "MEX": duplicate sticker(s) "8,9,10" ignored; first occurrence wins.')
    })
    test('empty exclusion result returns warning', () => {
      const result = normalize.normalizeLine('<>MEX,1-20')
      expect(result.line).toBeNull()
      expect(result.warnings).toContain(
        'Country "MEX": exclusion operator produces an empty sticker set; line skipped.'
      )
    })
    test('exclusion line with no sticker tokens skips line and warns', () => {
      const result = normalize.normalizeLine('<>MEX')
      expect(result.line).toBeNull()
      expect(result.warnings).toContain(
        'Country "MEX": exclusion line has no sticker tokens; line skipped.'
      )
    })
    test('exclusion repeat-count warning is emitted only once', () => {
      const result = normalize.normalizeLine('<>MEX,1(2),2(3),3(4)')
      expect(result.warnings.filter(w => w === 'Country "MEX": repeat counts are ignored in exclusion operator.')
      ).toHaveLength(0) // repeat-count warning removed; silently ignored per spec
    })
    test('exclusion silently ignores repeat counts and produces no warning', () => {
      const result = normalize.normalizeLine('<>MEX,1(2),2(3)')
      expect(result.line).toBe('MEX,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20')
      expect(result.warnings.length).toBe(0) // repeats silently ignored per spec; no warning emitted
    })
    test('empty input returns null without warning', () => {
      const result = normalize.normalizeLine('')
      expect(result.line).toBeNull()
      expect(result.warnings).toEqual([])
    })
    test('valid stickers are preserved when mixed-country tokens are removed', () => {
      const result = normalize.normalizeLine('MEX-1,ARG-2,ARG-3')
      expect(result.line).toBe('MEX,1')
      expect(result.warnings).toHaveLength(2)
    })
  })
})
